version: "3.6"

services:
  # duplicate speedtest for however many testing instances you want and change the requistie sub-params
  speedtest:
    image: headless-speedtest-za
    # compose is bad at rebuilding the image if upstream changes occur, so delete any contianers as needed
    build: https://raw.githubusercontent.com/H-SG/headless-speedtest-za/main/Dockerfile
    environment:
        # do we want to repeat the test
      - TEST_REPEAT=1
        # how often in minutes to repeat the speed test
      - REPEAT_TEST_INTERVAL=30
        # which minute of the hour to start the test interval, usefull for staggering multiple instances
      - REPEAT_TEST_ALIGNMENT_TIME=5
    network_mode: host
    restart: on-failure
    volumes: # remember to update these to be unique per speedtest service instance
      - ~/docker-data/speedtest-01/data:/app/data:rw
