[files]
    geckodriver_name = "/app/geckodriver"

[test_load]
    page_load_delay = 5
    save_test_screenshot = true
    screenshot_name = "/app/data/last_test.png"

[test_scoring]
    max_ping = 100
    min_download = 50
    min_upload = 50

[test_run]
    test_url = "http://speedtest.co.za/"
    test_trigger = "start-btn"
    score = true
    score_trigger = "starRating"
    specify_server = true
    server = "cpt"
    download_result = "download-result"
    upload_result = "upload-result"
    ping_result = "ping-result"
    test_repeat = 1
    # in minutes
    repeat_test_interval = 30
    # which minute of the hour to start the repeat cycle on
    repeat_test_time_align = 5 

[influx_db]
    save_influx = false
    influx_token = ""
    influx_org = ""
    influx_bucket = ""
    influx_url = ""

[csv_results]
    save_csv = true
    csv_name = "/app/data/headless-speedtest-results.csv"

[logging]
    log_name = "/app/data/headless-speedtest.log"
    log_level = "debug"
    log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
